@host = http://localhost:3000

GET {{host}}/api/students

###
GET {{host}}/api/students/6720e56a52fdd50b6cdb4771

###
POST {{host}}/api/students
Content-Type: application/json

{
    "name": "John Doe",
    "age": 20,
    "email": "john.doe@example.com",
    "phone": "1234567890",
    "address": "123 Main St",
    "city": "Anytown",
    "state": "CA",
    "zip": "12345"
}

###
PUT {{host}}/api/students/6720e56a52fdd50b6cdb4771
Content-Type: application/json

{
    "name": "Jane Doe"
}

###
DELETE {{host}}/api/students/6720e56a52fdd50b6cdb4771
